---
default_language_version:
  python: python3.12

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.3.0"
    hooks:
      - id: check-added-large-files
      - id: end-of-file-fixer
        exclude: .vscode
      - id: trailing-whitespace
      - id: check-ast
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: pretty-format-json
        exclude: .vscode
      - id: check-symlinks
      - id: check-shebang-scripts-are-executable
      - id: forbid-new-submodules
      - id: mixed-line-ending

  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: python
        pass_filenames: true
        types_or: [python, pyi]
      - id: isort
        name: isort
        entry: isort
        language: python
        pass_filenames: true
        types_or: [python, pyi]
      - id: pytest-check
        name: pytest-check
        entry: pytest
        args: ["--cov"]
        language: system
        pass_filenames: false
        always_run: true
